=== botblock/data/schema/list.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "title": "List",
    "description": "A bot list.",
    "required": [
        "id",
        "added",
        "name",
        "url",
        "icon",
        "language",
        "display",
        "defunct",
        "discord_only",
        "description",
        "api_docs",
        "api_post",
        "api_field",
        "api_shard_id",
        "api_shard_count",
        "api_shards",
        "api_get",
        "api_all",
        "view_bot",
        "bot_widget",
        "content",
        "owners",
        "discord",
        "features"
    ],
    "properties": {
        "id": {
            "$id": "#/properties/id",
            "type": "string",
            "title": "List Id",
            "description": "The domain of the bot list. Matches the file name."
        },
        "added": {
            "$id": "#/properties/added",
            "type": "integer",
            "title": "List added timestamp",
            "description": "Unix timestamp for when the list was added to BotBlock."
        },
        "name": {
            "$id": "#/properties/name",
            "type": "string",
            "title": "List name",
            "description": "The displayed name of the list."
        },
        "url": {
            "$id": "#/properties/url",
            "type": "string",
            "title": "List URL",
            "description": "The main URL to access the bot list."
        },
        "icon": {
            "$id": "#/properties/icon",
            "type": "string",
            "title": "List icon",
            "description": "A URL for an icon for the list."
        },
        "language": {
            "$id": "#/properties/language",
            "type": "string",
            "title": "List language(s)",
            "description": "The languages the list has support for."
        },
        "display": {
            "$id": "#/properties/display",
            "type": "integer",
            "title": "List display status",
            "description": "A flag for if the list is displayed on BotBlock, with 0 = hidden, 1 = displayed.",
            "enum": [
                0,
                1
            ]
        },
        "defunct": {
            "$id": "#/properties/defunct",
            "type": "integer",
            "title": "List defunct status",
            "description": "A flag for if the list is known to be defunct, with 0 = active, 1 = defunct.",
            "enum": [
                0,
                1
            ]
        },
        "discord_only": {
            "$id": "#/properties/discord_only",
            "type": "integer",
            "title": "List Discord-only status",
            "description": "A flag for if the list holds Discord bots only, with 0 = includes non-Discord, 1 = Discord-only.",
            "enum": [
                0,
                1
            ]
        },
        "description": {
            "$id": "#/properties/description",
            "type": [
                "string",
                "null"
            ],
            "title": "List description",
            "description": "The displayed description of the list."
        },
        "api_docs": {
            "$id": "#/properties/api_docs",
            "type": [
                "string",
                "null"
            ],
            "title": "List API docs URL",
            "description": "The URL to the API docs for the list, if known."
        },
        "api_post": {
            "$id": "#/properties/api_post",
            "type": [
                "string",
                "null"
            ],
            "title": "List API guild count POST endpoint",
            "description": "The endpoint URL for posting a bot's guild count to the list, if known, with `:id` as placeholder for bot Id."
        },
        "api_field": {
            "$id": "#/properties/api_field",
            "type": [
                "string",
                "null"
            ],
            "title": "List API count field name",
            "description": "The field name for guild count when posting a bot's guild count to the list, if known."
        },
        "api_shard_id": {
            "$id": "#/properties/api_shard_id",
            "type": [
                "string",
                "null"
            ],
            "title": "List API shard Id field name",
            "description": "The field name for shard Id when posting a bot's guild count to the list, if known."
        },
        "api_shard_count": {
            "$id": "#/properties/api_shard_count",
            "type": [
                "string",
                "null"
            ],
            "title": "List API shard count field name",
            "description": "The field name for shard count when posting a bot's guild count to the list, if known."
        },
        "api_shards": {
            "$id": "#/properties/api_shards",
            "type": [
                "string",
                "null"
            ],
            "title": "List API shards field name",
            "description": "The field name for shards when posting a bot's guild count to the list, if known."
        },
        "api_get": {
            "$id": "#/properties/api_get",
            "type": [
                "string",
                "null"
            ],
            "title": "List API bot GET endpoint",
            "description": "The endpoint URL for getting a bot from the list, if known, with `:id` as placeholder for bot Id."
        },
        "api_all": {
            "$id": "#/properties/api_all",
            "type": [
                "string",
                "null"
            ],
            "title": "List API all bots GET endpoint",
            "description": "The endpoint URL for getting all bots from the list, if known."
        },
        "view_bot": {
            "$id": "#/properties/view_bot",
            "type": [
                "string",
                "null"
            ],
            "title": "List view bot URL",
            "description": "The URL to the view a bot on the list, if known, with `:id` as placeholder for bot Id."
        },
        "bot_widget": {
            "$id": "#/properties/bot_widget",
            "type": [
                "string",
                "null"
            ],
            "title": "List bot widget URL",
            "description": "The URL to get a bot widget from the list, if known, with `:id` as placeholder for bot Id."
        },
        "content": {
            "$id": "#/properties/content",
            "type": [
                "string",
                "null"
            ],
            "title": "List notice content",
            "description": "The displayed notice content for the list, if any."
        },
        "owners": {
            "$id": "#/properties/owners",
            "type": [
                "string",
                "null"
            ],
            "pattern": "^(.{2,32}#\\d{4} \\(\\d{16,}\\))(, (.{2,32}#\\d{4} \\(\\d{16,}\\)))*$",
            "title": "List owners",
            "description": "Names of the list owners, if known."
        },
        "discord": {
            "$id": "#/properties/discord",
            "type": [
                "string",
                "null"
            ],
            "title": "List Discord invite URL",
            "description": "The URL invite for the list's Discord server, if known."
        },
        "features": {
            "$id": "#/properties/features",
            "type": "array",
            "title": "List features.",
            "description": "A list of feature Ids the bot list has. Ids must be valid feature Ids.",
            "items": {
                "type": "string",
                "title": "Feature Id",
                "description": "The Id of an existing feature."
            }
        }
    }
}

=== botblock/data/data/lists/fateslist.xyz.json
{
    "id": "fateslist.xyz",
    "added": 1613320331,
    "name": "Fates List",
    "url": "https://fateslist.xyz/",
    "icon": "https://api.fateslist.xyz/static/botlisticon.webp",
    "language": "English",
    "display": 1,
    "defunct": 1,
    "discord_only": 1,
    "description": "Find the best bots for your servers.",
    "api_docs": "https://docs.fateslist.xyz",
    "api_post": "https://api.fateslist.xyz/api/v2/bots/:id/stats",
    "api_field": "guild_count",
    "api_shard_id": null,
    "api_shard_count": "shard_count",
    "api_shards": "shards",
    "api_get": "https://api.fateslist.xyz/api/v2/bots/:id",
    "api_all": null,
    "view_bot": "https://fateslist.xyz/bot/:id",
    "bot_widget": "https://api.fateslist.xyz/api/v2/bots/:id/widget",
    "content": null,
    "owners": "Rootspring#6701 (563808552288780322), skylarr#6666 (790722073248661525), Builderb#0001 (190590364871032834)",
    "discord": "https://discord.gg/69Thz4teWm",
    "features": [
        "bot-resubmission",
        "bot-reviews",
        "html-long-description",
        "markdown-long-description",
        "custom-bot-github-link",
        "custom-bot-invite-link",
        "custom-bot-website-link",
        "discord-bot-support-link",
        "vanity-urls-for-all",
        "has-voting",
        "votes-sent-to-webhooks",
        "voting-data-exposed",
        "additional-bot-owners-editors",
        "has-categories-or-tags",
        "has-certification-program",
        "has-mobile-support",
        "has-search",
        "has-widget",
        "server-count-api"
    ]
}

=== botblock/data/data/lists/discordservices.net.json
{
    "id": "discordservices.net",
    "added": 1620045981,
    "name": "Discord Services",
    "url": "https://discordservices.net/",
    "icon": "https://discordservices.net/icon.png",
    "language": "English",
    "display": 1,
    "defunct": 0,
    "discord_only": 1,
    "description": "A brand new botlist that aims to deliver the best experience for its users and bot developers with unique features and tools.",
    "api_docs": "https://discordservices.net/docs/api",
    "api_post": "https://api.discordservices.net/bot/:id/stats",
    "api_field": "servers",
    "api_shard_id": null,
    "api_shard_count": "shards",
    "api_shards": null,
    "api_get": null,
    "api_all": null,
    "view_bot": "https://discordservices.net/bot/:id",
    "bot_widget": null,
    "content": null,
    "owners": "Builderb#0001 (190590364871032834)",
    "discord": "https://discord.gg/2JVesec7kM",
    "features": [
        "bot-resubmission",
        "markdown-long-description",
        "custom-bot-donate-link",
        "custom-bot-github-link",
        "custom-bot-invite-link",
        "custom-bot-support-link",
        "custom-bot-website-link",
        "discord-bot-support-link",
        "vanity-urls-for-all",
        "has-voting",
        "votes-sent-to-webhooks",
        "additional-bot-owners-editors",
        "has-categories-or-tags",
        "has-certification-program",
        "has-search",
        "has-widget",
        "server-count-api"
    ]
}

=== botblock/data/data/lists/discordbots.co.json
{
    "id": "discordbots.co",
    "added": 1592468403,
    "name": "Discord Bots",
    "url": "https://discordbots.co",
    "icon": "https://discordbots.co/favicon.png",
    "language": "English",
    "display": 1,
    "defunct": 0,
    "discord_only": 1,
    "description": "A new well-developed bot list from Vultrex Development. Here you can advertise your bot for free! ",
    "api_docs": "https://discordbots.co/api",
    "api_post": "https://api.discordbots.co/v1/public/bot/:id/stats",
    "api_field": "serverCount",
    "api_shard_id": null,
    "api_shard_count": "shardCount",
    "api_shards": null,
    "api_get": "https://api.discordbots.co/v1/public/bot/:id",
    "api_all": null,
    "view_bot": "https://discordbots.co/bot/:id",
    "bot_widget": null,
    "content": null,
    "owners": "Missy#0001 (157206689836171264)",
    "discord": "https://discord.gg/WeftAFp",
    "features": [
        "bot-resubmission",
        "bot-reviews",
        "html-long-description",
        "markdown-long-description",
        "custom-bot-donate-link",
        "custom-bot-github-link",
        "custom-bot-invite-link",
        "custom-bot-website-link",
        "discord-bot-support-link",
        "vanity-urls-for-all",
        "has-voting",
        "votes-sent-to-webhooks",
        "voting-data-exposed",
        "additional-bot-owners-editors",
        "has-categories-or-tags",
        "has-mobile-support",
        "has-search",
        "has-widget",
        "server-count-api"
    ]
}

=== botblock/data/data/lists/botlists.com.json
{
    "id": "botlists.com",
    "added": 1606421098,
    "name": "Astro Bot List",
    "url": "https://botlists.com/",
    "icon": "https://cdn.bot-list.xyz/7364djcas.png",
    "language": "English",
    "display": 1,
    "defunct": 1,
    "discord_only": 1,
    "description": "Astro bot list, just another discord bot lists where you show off your bots you made!",
    "api_docs": "https://botlists.com/api/docs",
    "api_post": "https://botlists.com/api/bot",
    "api_field": "guild_count",
    "api_shard_id": null,
    "api_shard_count": "shard_count",
    "api_shards": null,
    "api_get": "https://botlists.com/api/bot",
    "api_all": null,
    "view_bot": "https://botlists.com/bot/:id",
    "bot_widget": "https://botlists.com/bot/:id/widget",
    "content": "Website is not responding.",
    "owners": "QGV#2101 (185957154606284800)",
    "discord": "https://botlists.com/discord",
    "features": [
        "offers-paid-promotion",
        "bot-internationalisation-support",
        "html-long-description",
        "iframe-long-description",
        "markdown-long-description",
        "custom-bot-github-link",
        "custom-bot-support-link",
        "has-voting",
        "votes-sent-to-webhooks",
        "additional-bot-owners-editors",
        "has-categories-or-tags",
        "has-mobile-support",
        "has-search",
        "requires-owner-in-server",
        "server-count-api"
    ]
}

=== botblock/data/data/lists/discord.services.json
{
    "id": "discord.services",
    "added": 1532965633,
    "name": "Discord Services",
    "url": "https://discord.services/",
    "icon": "https://cdn.discordapp.com/icons/294505571317710849/a17f3c3ac54d09c04ab6c4f2f5dc9c12.png",
    "language": "English",
    "display": 1,
    "defunct": 1,
    "discord_only": 1,
    "description": null,
    "api_docs": "https://discord.services/api/",
    "api_post": "https://discord.services/api/bots/:id",
    "api_field": "server_count",
    "api_shard_id": null,
    "api_shard_count": null,
    "api_shards": null,
    "api_get": "https://discord.services/api/bots/:id",
    "api_all": "https://discord.services/api/bots",
    "view_bot": null,
    "bot_widget": null,
    "content": null,
    "owners": "Jazzibell#0069 (209219778206760961)",
    "discord": "https://discord.gg/hc6Wane",
    "features": [
        "custom-bot-invite-link"
    ]
}

=== botblock/data/data/lists/bots.idledev.org.json
{
    "id": "bots.idledev.org",
    "added": 1554996077,
    "name": "Idle Bot List",
    "url": "https://bots.idledev.org/",
    "icon": "https://cdn.discordapp.com/icons/521461252317249537/d3834340a5a6c466c1ac52d5aaf63fd0.png",
    "language": "English",
    "display": 1,
    "defunct": 1,
    "discord_only": 1,
    "description": null,
    "api_docs": null,
    "api_post": "https://bots.idledev.org/api/bot/:id/stats",
    "api_field": "server_count",
    "api_shard_id": null,
    "api_shard_count": null,
    "api_shards": null,
    "api_get": "https://bots.idledev.org/api/bot/:id/info",
    "api_all": null,
    "view_bot": "https://bots.idledev.org/bot/:id",
    "bot_widget": null,
    "content": null,
    "owners": "Tea Cup#9999 (338192747754160138)",
    "discord": "https://discord.gg/wU7B46S",
    "features": [
        "bot-resubmission",
        "bot-reviews",
        "html-long-description",
        "markdown-long-description",
        "has-voting",
        "additional-bot-owners-editors",
        "has-categories-or-tags",
        "has-search"
    ]
}

=== botblock/data/data/lists/discords.com.json
{
    "id": "discords.com",
    "added": 1532965633,
    "name": "Bots for Discord",
    "url": "https://discords.com/bots/",
    "icon": "https://cdn.discordapp.com/icons/374071874222686211/2fec188b91ebe43605065ee66a4df815.png",
    "language": "English",
    "display": 1,
    "defunct": 0,
    "discord_only": 1,
    "description": null,
    "api_docs": "https://docs.botsfordiscord.com",
    "api_post": "https://botsfordiscord.com/api/bot/:id",
    "api_field": "server_count",
    "api_shard_id": null,
    "api_shard_count": null,
    "api_shards": null,
    "api_get": "https://botsfordiscord.com/api/bot/:id",
    "api_all": null,
    "view_bot": "https://botsfordiscord.com/bots/:id",
    "bot_widget": "https://botsfordiscord.com/api/bot/:id/widget",
    "content": null,
    "owners": "Henry#1234 (165939947457478656)",
    "discord": "https://discord.gg/j5SRg4d",
    "features": [
        "bot-resubmission",
        "html-long-description",
        "markdown-long-description",
        "custom-bot-github-link",
        "custom-bot-invite-link",
        "custom-bot-support-link",
        "custom-bot-website-link",
        "discord-bot-support-link",
        "has-voting",
        "votes-sent-to-webhooks",
        "voting-data-exposed",
        "additional-bot-owners-editors",
        "has-categories-or-tags",
        "has-mobile-support",
        "has-search",
        "server-count-api"
    ]
}

=== botblock/data/data/lists/bladebotlist.xyz.json
{
    "id": "bladebotlist.xyz",
    "added": 1581889191,
    "name": "BladeBotList",
    "url": "https://bladebotlist.xyz/",
    "icon": "https://cdn.discordapp.com/icons/645281161949741064/fad8d2e250d653f180a547f728273f5a.png",
    "language": "English",
    "display": 1,
    "defunct": 0,
    "discord_only": 1,
    "description": "Discover a lot of new Discord bots for free and without login ! we check your bot in less than 12h* ",
    "api_docs": null,
    "api_post": "https://bladebotlist.xyz/api/bots/:id/stats",
    "api_field": "server_count",
    "api_shard_id": null,
    "api_shard_count": "shard_count",
    "api_shards": null,
    "api_get": "https://bladebotlist.xyz/api/bots/:id",
    "api_all": null,
    "view_bot": "https://bladebotlist.xyz/bot/:id",
    "bot_widget": "https://bladebotlist.xyz/bot/:id/widget.png",
    "content": null,
    "owners": "HiiZun#0001 (355995885085392896)",
    "discord": "https://discord.gg/pQc6ZRH",
    "features": [
        "bot-resubmission",
        "offers-paid-promotion",
        "markdown-long-description",
        "certified-bot-vanity-urls",
        "custom-bot-github-link",
        "custom-bot-invite-link",
        "custom-bot-support-link",
        "custom-bot-website-link",
        "discord-bot-support-link",
        "has-voting",
        "votes-sent-to-webhooks",
        "has-categories-or-tags",
        "has-mobile-support",
        "has-search",
        "server-count-api"
    ]
}
