=== botblock/data/schema/list.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "title": "List",
    "description": "A bot list.",
    "required": [
        "id",
        "added",
        "name",
        "url",
        "icon",
        "language",
        "display",
        "defunct",
        "discord_only",
        "description",
        "api_docs",
        "api_post",
        "api_field",
        "api_shard_id",
        "api_shard_count",
        "api_shards",
        "api_get",
        "api_all",
        "view_bot",
        "bot_widget",
        "content",
        "owners",
        "discord",
        "features"
    ],
    "properties": {
        "id": {
            "$id": "#/properties/id",
            "type": "string",
            "title": "List Id",
            "description": "The domain of the bot list. Matches the file name."
        },
        "added": {
            "$id": "#/properties/added",
            "type": "integer",
            "title": "List added timestamp",
            "description": "Unix timestamp for when the list was added to BotBlock."
        },
        "name": {
            "$id": "#/properties/name",
            "type": "string",
            "title": "List name",
            "description": "The displayed name of the list."
        },
        "url": {
            "$id": "#/properties/url",
            "type": "string",
            "title": "List URL",
            "description": "The main URL to access the bot list."
        },
        "icon": {
            "$id": "#/properties/icon",
            "type": "string",
            "title": "List icon",
            "description": "A URL for an icon for the list."
        },
        "language": {
            "$id": "#/properties/language",
            "type": "string",
            "title": "List language(s)",
            "description": "The languages the list has support for."
        },
        "display": {
            "$id": "#/properties/display",
            "type": "integer",
            "title": "List display status",
            "description": "A flag for if the list is displayed on BotBlock, with 0 = hidden, 1 = displayed.",
            "enum": [
                0,
                1
            ]
        },
        "defunct": {
            "$id": "#/properties/defunct",
            "type": "integer",
            "title": "List defunct status",
            "description": "A flag for if the list is known to be defunct, with 0 = active, 1 = defunct.",
            "enum": [
                0,
                1
            ]
        },
        "discord_only": {
            "$id": "#/properties/discord_only",
            "type": "integer",
            "title": "List Discord-only status",
            "description": "A flag for if the list holds Discord bots only, with 0 = includes non-Discord, 1 = Discord-only.",
            "enum": [
                0,
                1
            ]
        },
        "description": {
            "$id": "#/properties/description",
            "type": [
                "string",
                "null"
            ],
            "title": "List description",
            "description": "The displayed description of the list."
        },
        "api_docs": {
            "$id": "#/properties/api_docs",
            "type": [
                "string",
                "null"
            ],
            "title": "List API docs URL",
            "description": "The URL to the API docs for the list, if known."
        },
        "api_post": {
            "$id": "#/properties/api_post",
            "type": [
                "string",
                "null"
            ],
            "title": "List API guild count POST endpoint",
            "description": "The endpoint URL for posting a bot's guild count to the list, if known, with `:id` as placeholder for bot Id."
        },
        "api_field": {
            "$id": "#/properties/api_field",
            "type": [
                "string",
                "null"
            ],
            "title": "List API count field name",
            "description": "The field name for guild count when posting a bot's guild count to the list, if known."
        },
        "api_shard_id": {
            "$id": "#/properties/api_shard_id",
            "type": [
                "string",
                "null"
            ],
            "title": "List API shard Id field name",
            "description": "The field name for shard Id when posting a bot's guild count to the list, if known."
        },
        "api_shard_count": {
            "$id": "#/properties/api_shard_count",
            "type": [
                "string",
                "null"
            ],
            "title": "List API shard count field name",
            "description": "The field name for shard count when posting a bot's guild count to the list, if known."
        },
        "api_shards": {
            "$id": "#/properties/api_shards",
            "type": [
                "string",
                "null"
            ],
            "title": "List API shards field name",
            "description": "The field name for shards when posting a bot's guild count to the list, if known."
        },
        "api_get": {
            "$id": "#/properties/api_get",
            "type": [
                "string",
                "null"
            ],
            "title": "List API bot GET endpoint",
            "description": "The endpoint URL for getting a bot from the list, if known, with `:id` as placeholder for bot Id."
        },
        "api_all": {
            "$id": "#/properties/api_all",
            "type": [
                "string",
                "null"
            ],
            "title": "List API all bots GET endpoint",
            "description": "The endpoint URL for getting all bots from the list, if known."
        },
        "view_bot": {
            "$id": "#/properties/view_bot",
            "type": [
                "string",
                "null"
            ],
            "title": "List view bot URL",
            "description": "The URL to the view a bot on the list, if known, with `:id` as placeholder for bot Id."
        },
        "bot_widget": {
            "$id": "#/properties/bot_widget",
            "type": [
                "string",
                "null"
            ],
            "title": "List bot widget URL",
            "description": "The URL to get a bot widget from the list, if known, with `:id` as placeholder for bot Id."
        },
        "content": {
            "$id": "#/properties/content",
            "type": [
                "string",
                "null"
            ],
            "title": "List notice content",
            "description": "The displayed notice content for the list, if any."
        },
        "owners": {
            "$id": "#/properties/owners",
            "type": [
                "string",
                "null"
            ],
            "pattern": "^(.{2,32}#\\d{4} \\(\\d{16,}\\))(, (.{2,32}#\\d{4} \\(\\d{16,}\\)))*$",
            "title": "List owners",
            "description": "Names of the list owners, if known."
        },
        "discord": {
            "$id": "#/properties/discord",
            "type": [
                "string",
                "null"
            ],
            "title": "List Discord invite URL",
            "description": "The URL invite for the list's Discord server, if known."
        },
        "features": {
            "$id": "#/properties/features",
            "type": "array",
            "title": "List features.",
            "description": "A list of feature Ids the bot list has. Ids must be valid feature Ids.",
            "items": {
                "type": "string",
                "title": "Feature Id",
                "description": "The Id of an existing feature."
            }
        }
    }
}

=== botblock/data/data/lists/boatlist.ml.json
{
    "id": "boatlist.ml",
    "added": 1533208489,
    "name": "Boat List",
    "url": "https://boatlist.ml/",
    "icon": "https://cdn.discordapp.com/icons/425727209873997845/93665eebf1ef572917ec0e4c66be88ad.png",
    "language": "English",
    "display": 1,
    "defunct": 1,
    "discord_only": 1,
    "description": null,
    "api_docs": null,
    "api_post": "https://boatlist.ml/api/bots/:id/stats",
    "api_field": "server_count",
    "api_shard_id": null,
    "api_shard_count": null,
    "api_shards": null,
    "api_get": null,
    "api_all": null,
    "view_bot": null,
    "bot_widget": null,
    "content": "This list has shut down and has been replaced by a newer version under different management: https://botblock.org/lists/boatlist.xyz",
    "owners": "Kolkies#9876 (209609796704403456)",
    "discord": "https://discord.gg/SHEtT3x",
    "features": [
        "custom-bot-github-link"
    ]
}

=== botblock/data/data/lists/glennbotlist.xyz.json
{
    "id": "glennbotlist.xyz",
    "added": 1577741047,
    "name": "Glenn Bot List",
    "url": "https://glennbotlist.xyz",
    "icon": "https://cdn.discordapp.com/icons/623600255987875870/a_fdb1896f4a9e2b1d1ab74b6e1eadad7b.png",
    "language": "English",
    "display": 1,
    "defunct": 1,
    "discord_only": 1,
    "description": null,
    "api_docs": "https://docs.glennbotlist.xyz/",
    "api_post": "https://glennbotlist.xyz/api/bot/:id/stats",
    "api_field": "serverCount",
    "api_shard_id": null,
    "api_shard_count": "shardCount",
    "api_shards": null,
    "api_get": null,
    "api_all": null,
    "view_bot": "https://glennbotlist.xyz/bot/:id",
    "bot_widget": null,
    "content": null,
    "owners": "Jack Glenn#0806 (259649217255964672), DieselJS#1689 (414713250832449536)",
    "discord": "https://discord.gg/QeaNNRW",
    "features": [
        "custom-bot-github-link",
        "custom-bot-website-link",
        "additional-bot-owners-editors",
        "has-categories-or-tags"
    ]
}

=== botblock/data/data/lists/space-bot-list.xyz.json
{
    "id": "space-bot-list.xyz",
    "added": 1581887063,
    "name": "Space Bots List",
    "url": "https://space-bot-list.xyz/",
    "icon": "https://cdn.discordapp.com/attachments/595675239480950807/717039409916280863/SBL_new.png",
    "language": "English",
    "display": 1,
    "defunct": 0,
    "discord_only": 1,
    "description": "Space Bots List is botlist that you can find most of good bots, and learn from here how to make bot, with helpful staff",
    "api_docs": "https://spacebots.gitbook.io/tutorial-en/api/stats",
    "api_post": "https://space-bot-list.xyz/api/bots/:id",
    "api_field": "guilds",
    "api_shard_id": null,
    "api_shard_count": null,
    "api_shards": null,
    "api_get": "https://space-bot-list.xyz/api/bots/:id",
    "api_all": null,
    "view_bot": "https://space-bot-list.xyz/bots/:id",
    "bot_widget": null,
    "content": null,
    "owners": "MR.Nak#9011 (471973265594908673), Derpy#6666 (388320576407863297)",
    "discord": "https://discord.gg/jkwDfC7",
    "features": [
        "markdown-long-description",
        "custom-bot-github-link",
        "custom-bot-support-link",
        "custom-bot-website-link",
        "voting-data-exposed",
        "additional-bot-owners-editors",
        "has-mobile-support",
        "requires-owner-in-server"
    ]
}

=== botblock/data/data/lists/boatspace.xyz.json
{
    "id": "boatspace.xyz",
    "added": 1620045793,
    "name": "BoatSpace",
    "url": "https://boatspace.xyz/",
    "icon": "https://boatspace.xyz/cdn/img/boat.png",
    "language": "English",
    "display": 1,
    "defunct": 0,
    "discord_only": 1,
    "description": "The best bot list on the internet! BoatSpace enables users to find the best bot for their Discord server fast, easily, and for free!",
    "api_docs": "https://docs.boatspace.xyz/",
    "api_post": "https://boatspace.xyz/api/bots/:id",
    "api_field": "server_count",
    "api_shard_id": null,
    "api_shard_count": "shard_count",
    "api_shards": null,
    "api_get": "https://boatspace.xyz/api/bots/:id",
    "api_all": null,
    "view_bot": null,
    "bot_widget": "https://boatspace.xyz/api/bots/:id/widget?type=png",
    "content": null,
    "owners": "HGDev#9997 (242734840829575169)",
    "discord": "https://discord.gg/bVakMZY",
    "features": [
        "has-ads-on-site",
        "html-long-description",
        "markdown-long-description",
        "certified-bot-vanity-urls",
        "custom-bot-support-link",
        "custom-bot-website-link",
        "has-voting",
        "has-certification-program",
        "has-mobile-support"
    ]
}

=== botblock/data/data/lists/bhbotlist.tech.json
{
    "id": "bhbotlist.tech",
    "added": 1658768359,
    "name": "BHbotlist",
    "url": "https://bhbotlist.tech/",
    "icon": "https://cdn.discordapp.com/attachments/671391805715120148/1001172244707410010/logo.png",
    "language": "English",
    "display": 1,
    "defunct": 0,
    "discord_only": 1,
    "description": "Spice up your Discord experience with our diverse range of Discord bots",
    "api_docs": "https://docs.bhbotlist.tech/",
    "api_post": "https://bhbotlist.tech/api/bot/:id",
    "api_field": "server_count",
    "api_shard_id": null,
    "api_shard_count": "shard_count",
    "api_shards": null,
    "api_get": "https://bhbotlist.tech/api/bot/:id",
    "api_all": null,
    "view_bot": "https://bhbotlist.tech/bot/:id",
    "bot_widget": "https://bhbotlist.tech/bot/:id/embed",
    "content": null,
    "owners": "{Ansh}#0607 (671390595184459782), Blacky#9125 (959276033683628122)",
    "discord": "https://discord.gg/xtx49HtRMb",
    "features": [
        "bot-resubmission",
        "offers-paid-promotion",
        "unique bots",
        "html-long-description",
        "certified-bot-vanity-urls",
        "custom-bot-github-link",
        "custom-bot-invite-link",
        "custom-bot-support-link",
        "custom-bot-website-link",
        "discord-bot-support-link",
        "has-voting",
        "has-categories-or-tags",
        "has-search",
        "server-count-api"
    ]
}

=== botblock/data/data/lists/discordbotindex.com.json
{
    "id": "discordbotindex.com",
    "added": 1539030775,
    "name": "Discord Bot Index",
    "url": "https://discordbotindex.com/",
    "icon": "https://cdn.discordapp.com/icons/482922868410417163/bcb70a74c152d82021a9421d55bc3ec3.png",
    "language": "English",
    "display": 1,
    "defunct": 1,
    "discord_only": 1,
    "description": null,
    "api_docs": "https://discordbotindex.com/documentation",
    "api_post": "https://discordbotindex.com/apiv1/bot/:id",
    "api_field": "server_count",
    "api_shard_id": null,
    "api_shard_count": null,
    "api_shards": null,
    "api_get": "https://discordbotindex.com/apiv1/bot/:id",
    "api_all": null,
    "view_bot": "https://discordbotindex.com/bot/:id",
    "bot_widget": null,
    "content": "This list has shut down and been merged into discord.boats",
    "owners": "LiquidBlast, SamuraiStacks#5873 (439373663905513473), Kirb#0001 (303943082108518400), ohlookitsderpy#3939 (145557815287611393), ðŸŽ€ QuantumCat ðŸŽ€#2107 (130769947583447040)",
    "discord": "https://discord.gg/9jkAUF3",
    "features": [
        "custom-bot-github-link",
        "custom-bot-support-link",
        "custom-bot-website-link",
        "discord-bot-support-link",
        "voting-data-exposed",
        "has-mobile-support"
    ]
}

=== botblock/data/data/lists/discord.rovelstars.com.json
{
    "id": "discord.rovelstars.com",
    "added": 1639455345,
    "name": "Rovel Discord List",
    "url": "https://discord.rovelstars.com",
    "icon": "https://discord.rovelstars.com/assets/img/bot/logo.svg",
    "language": "English",
    "display": 1,
    "defunct": 0,
    "discord_only": 1,
    "description": "Imagine a place - where you get to find everything about discord! Ranging from bots, to users, servers, templates, banners, stickers and emojis!",
    "api_docs": null,
    "api_post": "https://discord.rovelstars.com/api/bots/:id/servers",
    "api_field": "count",
    "api_shard_id": null,
    "api_shard_count": null,
    "api_shards": null,
    "api_get": "https://discord.rovelstars.com/api/v1/bots/:id",
    "api_all": "https://discord.rovelstars.com/api/v1/bots",
    "view_bot": "https://discord.rovelstars.com/bots/:id",
    "bot_widget": null,
    "content": null,
    "owners": "Ren Hiyama#1800 (889439979686739998)",
    "discord": "https://dscrdly.com/server",
    "features": [
        "site-internationalisation-support",
        "iframe-long-description",
        "custom-bot-github-link",
        "discord-bot-support-link",
        "has-voting",
        "voting-data-exposed",
        "has-mobile-support",
        "server-count-api",
        "html-long-description",
        "markdown-long-description",
        "html-long-description",
        "markdown-long-description",
        "custom-bot-donate-link",
        "custom-bot-invite-link",
        "custom-bot-website-link",
        "vanity-urls-for-all",
        "votes-sent-to-webhooks",
        "additional-bot-owners-editors",
        "has-search",
        "requires-owner-in-server"
    ]
}

=== botblock/data/data/lists/discordbot.world.json
{
    "id": "discordbot.world",
    "added": 1532965633,
    "name": "Discord Bot World",
    "url": "https://discordbot.world/",
    "icon": "https://cdn.discordapp.com/icons/396440418507816960/aed0c9184d1e3abf28be02599b2c0f41.png",
    "language": "English",
    "display": 0,
    "defunct": 1,
    "discord_only": 1,
    "description": null,
    "api_docs": "https://discordbot.world/docs",
    "api_post": "https://discordbot.world/api/bot/:id/stats",
    "api_field": "guild_count",
    "api_shard_id": null,
    "api_shard_count": null,
    "api_shards": "shards",
    "api_get": "https://discordbot.world/api/bot/:id",
    "api_all": "https://discordbot.world/api/bots",
    "view_bot": "https://discordbot.world/bot/:id",
    "bot_widget": null,
    "content": "The site does not seem to be approving bots anymore, the owner claims he will 'work on the site' when he has time. This has been an on-going issue for over a year and is technically defunct.",
    "owners": "Dustin#1999 (156114103033790464)",
    "discord": "https://discord.gg/eneuuys",
    "features": [
        "custom-bot-github-link",
        "custom-bot-invite-link",
        "custom-bot-support-link",
        "custom-bot-website-link",
        "discord-bot-support-link",
        "voting-data-exposed",
        "additional-bot-owners-editors",
        "has-mobile-support"
    ]
}
