=== botblock/data/schema/list.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "title": "List",
    "description": "A bot list.",
    "required": [
        "id",
        "added",
        "name",
        "url",
        "icon",
        "language",
        "display",
        "defunct",
        "discord_only",
        "description",
        "api_docs",
        "api_post",
        "api_field",
        "api_shard_id",
        "api_shard_count",
        "api_shards",
        "api_get",
        "api_all",
        "view_bot",
        "bot_widget",
        "content",
        "owners",
        "discord",
        "features"
    ],
    "properties": {
        "id": {
            "$id": "#/properties/id",
            "type": "string",
            "title": "List Id",
            "description": "The domain of the bot list. Matches the file name."
        },
        "added": {
            "$id": "#/properties/added",
            "type": "integer",
            "title": "List added timestamp",
            "description": "Unix timestamp for when the list was added to BotBlock."
        },
        "name": {
            "$id": "#/properties/name",
            "type": "string",
            "title": "List name",
            "description": "The displayed name of the list."
        },
        "url": {
            "$id": "#/properties/url",
            "type": "string",
            "title": "List URL",
            "description": "The main URL to access the bot list."
        },
        "icon": {
            "$id": "#/properties/icon",
            "type": "string",
            "title": "List icon",
            "description": "A URL for an icon for the list."
        },
        "language": {
            "$id": "#/properties/language",
            "type": "string",
            "title": "List language(s)",
            "description": "The languages the list has support for."
        },
        "display": {
            "$id": "#/properties/display",
            "type": "integer",
            "title": "List display status",
            "description": "A flag for if the list is displayed on BotBlock, with 0 = hidden, 1 = displayed.",
            "enum": [
                0,
                1
            ]
        },
        "defunct": {
            "$id": "#/properties/defunct",
            "type": "integer",
            "title": "List defunct status",
            "description": "A flag for if the list is known to be defunct, with 0 = active, 1 = defunct.",
            "enum": [
                0,
                1
            ]
        },
        "discord_only": {
            "$id": "#/properties/discord_only",
            "type": "integer",
            "title": "List Discord-only status",
            "description": "A flag for if the list holds Discord bots only, with 0 = includes non-Discord, 1 = Discord-only.",
            "enum": [
                0,
                1
            ]
        },
        "description": {
            "$id": "#/properties/description",
            "type": [
                "string",
                "null"
            ],
            "title": "List description",
            "description": "The displayed description of the list."
        },
        "api_docs": {
            "$id": "#/properties/api_docs",
            "type": [
                "string",
                "null"
            ],
            "title": "List API docs URL",
            "description": "The URL to the API docs for the list, if known."
        },
        "api_post": {
            "$id": "#/properties/api_post",
            "type": [
                "string",
                "null"
            ],
            "title": "List API guild count POST endpoint",
            "description": "The endpoint URL for posting a bot's guild count to the list, if known, with `:id` as placeholder for bot Id."
        },
        "api_field": {
            "$id": "#/properties/api_field",
            "type": [
                "string",
                "null"
            ],
            "title": "List API count field name",
            "description": "The field name for guild count when posting a bot's guild count to the list, if known."
        },
        "api_shard_id": {
            "$id": "#/properties/api_shard_id",
            "type": [
                "string",
                "null"
            ],
            "title": "List API shard Id field name",
            "description": "The field name for shard Id when posting a bot's guild count to the list, if known."
        },
        "api_shard_count": {
            "$id": "#/properties/api_shard_count",
            "type": [
                "string",
                "null"
            ],
            "title": "List API shard count field name",
            "description": "The field name for shard count when posting a bot's guild count to the list, if known."
        },
        "api_shards": {
            "$id": "#/properties/api_shards",
            "type": [
                "string",
                "null"
            ],
            "title": "List API shards field name",
            "description": "The field name for shards when posting a bot's guild count to the list, if known."
        },
        "api_get": {
            "$id": "#/properties/api_get",
            "type": [
                "string",
                "null"
            ],
            "title": "List API bot GET endpoint",
            "description": "The endpoint URL for getting a bot from the list, if known, with `:id` as placeholder for bot Id."
        },
        "api_all": {
            "$id": "#/properties/api_all",
            "type": [
                "string",
                "null"
            ],
            "title": "List API all bots GET endpoint",
            "description": "The endpoint URL for getting all bots from the list, if known."
        },
        "view_bot": {
            "$id": "#/properties/view_bot",
            "type": [
                "string",
                "null"
            ],
            "title": "List view bot URL",
            "description": "The URL to the view a bot on the list, if known, with `:id` as placeholder for bot Id."
        },
        "bot_widget": {
            "$id": "#/properties/bot_widget",
            "type": [
                "string",
                "null"
            ],
            "title": "List bot widget URL",
            "description": "The URL to get a bot widget from the list, if known, with `:id` as placeholder for bot Id."
        },
        "content": {
            "$id": "#/properties/content",
            "type": [
                "string",
                "null"
            ],
            "title": "List notice content",
            "description": "The displayed notice content for the list, if any."
        },
        "owners": {
            "$id": "#/properties/owners",
            "type": [
                "string",
                "null"
            ],
            "pattern": "^(.{2,32}#\\d{4} \\(\\d{16,}\\))(, (.{2,32}#\\d{4} \\(\\d{16,}\\)))*$",
            "title": "List owners",
            "description": "Names of the list owners, if known."
        },
        "discord": {
            "$id": "#/properties/discord",
            "type": [
                "string",
                "null"
            ],
            "title": "List Discord invite URL",
            "description": "The URL invite for the list's Discord server, if known."
        },
        "features": {
            "$id": "#/properties/features",
            "type": "array",
            "title": "List features.",
            "description": "A list of feature Ids the bot list has. Ids must be valid feature Ids.",
            "items": {
                "type": "string",
                "title": "Feature Id",
                "description": "The Id of an existing feature."
            }
        }
    }
}

=== botblock/data/data/lists/yabl.xyz.json
{
    "id": "yabl.xyz",
    "added": 1564607076,
    "name": "Yet Another Bot List",
    "url": "https://yabl.xyz/",
    "icon": "https://i.imgur.com/OFiMern.png",
    "language": "English",
    "display": 1,
    "defunct": 0,
    "discord_only": 1,
    "description": null,
    "api_docs": "https://yabl.xyz/api",
    "api_post": "https://yabl.xyz/api/bot/:id/stats",
    "api_field": "guildCount",
    "api_shard_id": null,
    "api_shard_count": null,
    "api_shards": null,
    "api_get": "https://yabl.xyz/api/bot/:id",
    "api_all": "https://yabl.xyz/api/bots/all",
    "view_bot": "https://yabl.xyz/bot/:id",
    "bot_widget": null,
    "content": null,
    "owners": "! craftxbox#4738 (153353572711530496), ry00001#3487 (190544080164487168)",
    "discord": "https://discord.gg/vXeUnzZ",
    "features": [
        "markdown-long-description",
        "custom-bot-github-link",
        "custom-bot-support-link",
        "custom-bot-website-link",
        "discord-bot-support-link"
    ]
}

=== botblock/data/data/lists/automacord.xyz.json
{
    "id": "automacord.xyz",
    "added": 1535444547,
    "name": "AutomaCord",
    "url": "https://automacord.xyz/",
    "icon": "https://cdn.discordapp.com/icons/483344253963993113/3661052b289c88dfffd5a91080d6beae.png",
    "language": "English",
    "display": 1,
    "defunct": 1,
    "discord_only": 1,
    "description": null,
    "api_docs": null,
    "api_post": null,
    "api_field": null,
    "api_shard_id": null,
    "api_shard_count": null,
    "api_shards": null,
    "api_get": null,
    "api_all": null,
    "view_bot": "https://automacord.xyz/bot/:id",
    "bot_widget": null,
    "content": null,
    "owners": "Kromatic#0420 (180093157554388993)",
    "discord": "https://discord.gg/XQT4DEt",
    "features": [
        "markdown-long-description",
        "custom-bot-invite-link",
        "additional-bot-owners-editors"
    ]
}

=== botblock/data/data/lists/topcord.xyz.json
{
    "id": "topcord.xyz",
    "added": 1597352795,
    "name": "TopCord",
    "url": "https://topcord.xyz/",
    "icon": "https://topcord.xyz/logo.png",
    "language": "English",
    "display": 1,
    "defunct": 0,
    "discord_only": 0,
    "description": "TopCord is the best Discord Bot List for finding the Discord bots that suit your server.",
    "api_docs": "https://docs.topcord.xyz/#/",
    "api_post": "https://api.topcord.xyz/bot/:id/stats",
    "api_field": "guilds",
    "api_shard_id": null,
    "api_shard_count": "shards",
    "api_shards": null,
    "api_get": "https://api.topcord.xyz/bot/:id",
    "api_all": "https://api.topcord.xyz/bots",
    "view_bot": "https://topcord.xyz/bot/:id",
    "bot_widget": "https://topcord.xyz/widget/bot/:id",
    "content": null,
    "owners": "ElectricReality#2009 (319680837320704003)",
    "discord": "https://discord.gg/zira",
    "features": [
        "bot-resubmission",
        "has-ads-on-site",
        "html-long-description",
        "iframe-long-description",
        "markdown-long-description",
        "certified-bot-vanity-urls",
        "custom-bot-support-link",
        "custom-bot-website-link",
        "discord-bot-support-link",
        "has-voting",
        "votes-sent-to-webhooks",
        "voting-data-exposed",
        "has-categories-or-tags",
        "has-mobile-support",
        "has-search",
        "has-widget",
        "requires-owner-in-server",
        "server-count-api"
    ]
}

=== botblock/data/data/lists/listcord.com.json
{
    "id": "listcord.com",
    "added": 1532965633,
    "name": "Listcord",
    "url": "https://listcord.com/",
    "icon": "https://cdn.discordapp.com/icons/692858882153775164/2a6fac8a8090bc3b9e4f490ba978bf93.png",
    "language": "English",
    "display": 0,
    "defunct": 0,
    "discord_only": 1,
    "description": null,
    "api_docs": null,
    "api_post": null,
    "api_field": null,
    "api_shard_id": null,
    "api_shard_count": null,
    "api_shards": null,
    "api_get": null,
    "api_all": null,
    "view_bot": null,
    "bot_widget": null,
    "content": "Owner: \"This project is currently paused due to changes in my personal life and to prioritize other projects of mine. Please understand this decision, and know that I will eventually get back to this.\", site redirects to Discord sercer",
    "owners": "chewy#0001 (219592873228763147)",
    "discord": "https://discord.gg/f3dwWxf",
    "features": [
        "custom-bot-invite-link",
        "custom-bot-website-link",
        "discord-bot-support-link",
        "voting-data-exposed",
        "additional-bot-owners-editors"
    ]
}

=== botblock/data/data/lists/discordmusicbots.com.json
{
    "id": "discordmusicbots.com",
    "added": 1533208489,
    "name": "Discord Music Bots",
    "url": "https://www.discordmusicbots.com/",
    "icon": "https://www.discordmusicbots.com/logo.png",
    "language": "English",
    "display": 1,
    "defunct": 1,
    "discord_only": 1,
    "description": null,
    "api_docs": null,
    "api_post": null,
    "api_field": null,
    "api_shard_id": null,
    "api_shard_count": null,
    "api_shards": null,
    "api_get": null,
    "api_all": null,
    "view_bot": null,
    "bot_widget": null,
    "content": "This list appears to be offline and no longer active.",
    "owners": "spong#3338 (87164639695110144)",
    "discord": null,
    "features": [
        "custom-bot-invite-link",
        "custom-bot-support-link",
        "custom-bot-website-link",
        "discord-bot-support-link",
        "has-categories-or-tags",
        "has-mobile-support"
    ]
}

=== botblock/data/data/lists/discordboats.club.json
{
    "id": "discordboats.club",
    "added": 1533208489,
    "name": "Discord Boats",
    "url": "https://discordboats.club/",
    "icon": "https://cdn.discordapp.com/icons/421630709585805312/15fa554458a690010d7575fbd02839a7.png",
    "language": "English",
    "display": 1,
    "defunct": 1,
    "discord_only": 1,
    "description": null,
    "api_docs": null,
    "api_post": "https://discordboats.club/api/public/bot/stats",
    "api_field": "server_count",
    "api_shard_id": null,
    "api_shard_count": null,
    "api_shards": null,
    "api_get": null,
    "api_all": null,
    "view_bot": "https://discordboats.club/bot/:id",
    "bot_widget": "https://discordboats.club/bot/:id/widget.png",
    "content": "After inactivity and a long period of no development, the list was sold to MrSheldon and merged into discord.boats.",
    "owners": "Anthony#3912 (233823931830632449)",
    "discord": "https://discord.gg/qRarbNz",
    "features": [
        "markdown-long-description",
        "custom-bot-github-link",
        "custom-bot-invite-link",
        "custom-bot-website-link",
        "vanity-urls-for-all",
        "voting-data-exposed",
        "has-mobile-support"
    ]
}

=== botblock/data/data/lists/bots.ondiscord.xyz.json
{
    "id": "bots.ondiscord.xyz",
    "added": 1532965633,
    "name": "Bots on Discord",
    "url": "https://bots.ondiscord.xyz/",
    "icon": "https://cdn.discordapp.com/icons/446425626988249089/c9599b1e0fdb902b81d93468ada512cf.png",
    "language": "English",
    "display": 1,
    "defunct": 0,
    "discord_only": 1,
    "description": "Easily find and share Discord bots",
    "api_docs": "https://bots.ondiscord.xyz/info/api",
    "api_post": "https://bots.ondiscord.xyz/bot-api/bots/:id/guilds",
    "api_field": "guildCount",
    "api_shard_id": null,
    "api_shard_count": null,
    "api_shards": null,
    "api_get": null,
    "api_all": null,
    "view_bot": "https://bots.ondiscord.xyz/bots/:id",
    "bot_widget": "https://bots.ondiscord.xyz/bots/:id/embed",
    "content": null,
    "owners": "Brussell#0660 (95286900801146880)",
    "discord": "https://discord.gg/bvm6vSv",
    "features": [
        "bot-resubmission",
        "markdown-long-description",
        "custom-bot-invite-link",
        "custom-bot-website-link",
        "discord-bot-support-link",
        "additional-bot-owners-editors",
        "has-categories-or-tags",
        "has-mobile-support"
    ]
}

=== botblock/data/data/lists/discordbots.group.json
{
    "id": "discordbots.group",
    "added": 1532965633,
    "name": "Discord Bots Group",
    "url": "https://discordbots.group/",
    "icon": "https://cdn.discordapp.com/icons/447469952044105728/b725a3f9bf422b18480d3a9f829be06a.png",
    "language": "English",
    "display": 1,
    "defunct": 1,
    "discord_only": 1,
    "description": null,
    "api_docs": "https://docs.discordbots.group/",
    "api_post": "https://api.discordbots.group/v1/bot/:id",
    "api_field": "server_count",
    "api_shard_id": null,
    "api_shard_count": null,
    "api_shards": "shards",
    "api_get": "https://api.discordbots.group/v1/bot/:id",
    "api_all": null,
    "view_bot": "https://discordbots.group/bot/:id",
    "bot_widget": null,
    "content": null,
    "owners": "DetectiveHuman#1234 (449653897695461376)",
    "discord": "https://discord.gg/9jJtKRc",
    "features": [
        "markdown-long-description",
        "custom-bot-github-link",
        "custom-bot-invite-link",
        "custom-bot-support-link",
        "custom-bot-website-link",
        "discord-bot-support-link",
        "voting-data-exposed",
        "additional-bot-owners-editors",
        "has-categories-or-tags",
        "has-mobile-support"
    ]
}
